import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { NewNote } from './components/newNote.js';
import { AdamantineNotes } from './components/home.js';
import { DisplayNotes } from './components/displayNotes.js'

export default function Home() {
  return (
    <>
      <Head>
        <title>✦ Adamantine Notes ✦</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.adamantineHeader} >
          <AdamantineNotes />
        </div>
        <div className={styles.newNote}>
          <NewNote />
        </div>
        <div className={styles.displayedNote} >
          <DisplayNotes />
        </div>
      </main>
    </>
  )
}
